<?php
namespace Native5\Tests\Services\Account;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-31 at 20:52:12.
 */
class DefaultAccountManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DefaultAccountManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DefaultAccountManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Native5\Services\Account\DefaultAccountManager::getAccountDetails
     * @todo   Implement testGetAccountDetails().
     */
    public function testGetAccountDetails()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Native5\Services\Account\DefaultAccountManager::getApps
     * @todo   Implement testGetApps().
     */
    public function testGetApps()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Native5\Services\Account\DefaultAccountManager::createApp
     * @todo   Implement testCreateApp().
     */
    public function testCreateApp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Native5\Services\Account\DefaultAccountManager::uploadApp
     * @todo   Implement testUploadApp().
     */
    public function testUploadApp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
